title: Jimmy Tran
description: Machine Learning Engineer & Educator in Data Science
linkedin: "https://www.linkedin.com/in/jimmyqtran"
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
