title: Jimmy Tran
description: Machine Learning Engineer & Educator based in SF, CA
linkedin: "https://www.linkedin.com/in/jimmyqtran"
logo: /assets/img/logo.png
show_downloads: false
google_analytics: G-0WBF1H5BEC
theme: jekyll-theme-minimal
